[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome6"

[theme.overrides]
separator = " "

[[block]]
block = "disk_space"
info_type = "available"
format = "$icon $available"

[[block]]
block = "battery"
format = "$icon $percentage {$time}h $power"
device = "BAT0"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "temperature"
format = "$icon $max"
idle = 50
info = 70
warning = 80
# icons_format = " "

[[block]]
block = "cpu"
format = "$icon CPU $utilization"
# icons_format = " "

[[block]]
block = "memory"
format = "$icon MEM $mem_used_percents"
# format_alt = "$icon MEM $swap_used_percents"
# icons_format = " "

[[block]]
block = "time"
format = "$icon $timestamp.datetime(f:'%F %R')"
# icons_format = " "
